server:
  port: 6970

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel_management
    username: root
    password: Halodoc@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update