server:
  port: 6971

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rating_management
    username: root
    password: Halodoc@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true